apiVersion: v1
kind: Service
metadata:
  name: example-java-test-1
spec:
  selector:
    app: example-java-test-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: example-java-test-1-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: example-java-test-1.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: example-java-test-1
#             port:
#               number: 80
