apiVersion: apps/v1
kind: Deployment
metadata:
  name: jk7-mar-5
  labels:
    app: jk7-mar-5
    backstage.io/kubernetes-id: jk7-mar-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jk7-mar-5
  template:
    metadata:
      labels:
        app: jk7-mar-5
        backstage.io/kubernetes-id: jk7-mar-5
    spec:
      containers:
        - name: jk7-mar-5
          image: jaykumark7/jk7-mar-5:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


