apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-repo-developer-13
  labels:
    app: example-repo-developer-13
    backstage.io/kubernetes-id: example-repo-developer-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-repo-developer-13
  template:
    metadata:
      labels:
        app: example-repo-developer-13
        backstage.io/kubernetes-id: example-repo-developer-13
    spec:
      containers:
        - name: example-repo-developer-13
          image: jaykumark7/example-repo-developer-13:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


