apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-ssp-06
  labels:
    app: backstage-ssp-06
    backstage.io/kubernetes-id: backstage-ssp-06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-ssp-06
  template:
    metadata:
      labels:
        app: backstage-ssp-06
        backstage.io/kubernetes-id: backstage-ssp-06
    spec:
      containers:
        - name: backstage-ssp-06
          image: jaykumark7/backstage-ssp-06:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


