apiVersion: apps/v1
kind: Deployment
metadata:
  name: jk-demo-test-4
  labels:
    app: jk-demo-test-4
    backstage.io/kubernetes-id: jk-demo-test-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jk-demo-test-4
  template:
    metadata:
      labels:
        app: jk-demo-test-4
        backstage.io/kubernetes-id: jk-demo-test-4
    spec:
      containers:
        - name: jk-demo-test-4
          image: jaykumark7/jk-demo-test-4:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


