apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-3-developer3
  labels:
    app: source-3-developer3
    backstage.io/kubernetes-id: source-3-developer3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source-3-developer3
  template:
    metadata:
      labels:
        app: source-3-developer3
        backstage.io/kubernetes-id: source-3-developer3
    spec:
      containers:
        - name: source-3-developer3
          image: jaykumark7/source-3-developer3:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


