apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-python-test-7
  namespace: prod
  labels:
    app: example-python-test-7
    backstage.io/kubernetes-id: example-python-test-7
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-python-test-7
  template:
    metadata:
      labels:
        app: example-python-test-7
        backstage.io/kubernetes-id: example-python-test-7
        environment: prod
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
        - name: example-python-test-7
          image: jaykumark7/example-python-test-7:1.0.3
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "prod"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
              ephemeral-storage: "50Mi"
            limits:
              memory: "128Mi"
              cpu: "100m"
              ephemeral-storage: "100Mi"
