apiVersion: v1
kind: Service
metadata:
  name: java-template-2
  namespace: dev
  labels:
    backstage.io/kubernetes-id: java-template-2
spec:
  selector:
    app: java-template-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
