apiVersion: apps/v1
kind: Deployment
metadata:
  name: march-23-test
  labels:
    app: march-23-test
    backstage.io/kubernetes-id: march-23-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: march-23-test
  template:
    metadata:
      labels:
        app: march-23-test
        backstage.io/kubernetes-id: march-23-test
    spec:
      containers:
        - name: march-23-test
          image: jaykumark7/march-23-test:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


