apiVersion: v1
kind: Service
metadata:
  name: jk7test189
spec:
  selector:
    app: jk7test189
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: LoadBalancer

