apiVersion: v1
kind: Service
metadata:
  name: jk7test1221
spec:
  selector:
    app: jk7test1221
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: LoadBalancer

