apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-3-app-developer1
  labels:
    app: source-3-app-developer1
    backstage.io/kubernetes-id: source-3-app-developer1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source-3-app-developer1
  template:
    metadata:
      labels:
        app: source-3-app-developer1
        backstage.io/kubernetes-id: source-3-app-developer1
    spec:
      containers:
        - name: source-3-app-developer1
          image: jaykumark7/source-3-app-developer1:1.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


