apiVersion: v1
kind: Service
metadata:
  name: goldenimagetest2
spec:
  selector:
    app: goldenimagetest2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

  type: LoadBalancer
