apiVersion: apps/v1
kind: Deployment
metadata:
  name: march-demo-6
  labels:
    app: march-demo-6
    backstage.io/kubernetes-id: march-demo-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: march-demo-6
  template:
    metadata:
      labels:
        app: march-demo-6
        backstage.io/kubernetes-id: march-demo-6
    spec:
      containers:
        - name: march-demo-6
          image: jaykumark7/march-demo-6:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


