apiVersion: apps/v1
kind: Deployment
metadata:
  name: jk7-mar-4
  labels:
    app: jk7-mar-4
    backstage.io/kubernetes-id: jk7-mar-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jk7-mar-4
  template:
    metadata:
      labels:
        app: jk7-mar-4
        backstage.io/kubernetes-id: jk7-mar-4
    spec:
      containers:
        - name: jk7-mar-4
          image: jaykumark7/jk7-mar-4:1.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


