apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-repo-main
  labels:
    app: example-repo-main
    backstage.io/kubernetes-id: example-repo-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-repo-main
  template:
    metadata:
      labels:
        app: example-repo-main
        backstage.io/kubernetes-id: example-repo-main
    spec:
      containers:
        - name: example-repo-main
          image: jaykumark7/example-repo-main:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


