apiVersion: v1
kind: Service
metadata:
  name: example-repo-developer-14
spec:
  selector:
    app: example-repo-developer-14
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: LoadBalancer

