apiVersion: apps/v1
kind: Deployment
metadata:
  name: jk-demo-test-10
  labels:
    app: jk-demo-test-10
    backstage.io/kubernetes-id: jk-demo-test-10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jk-demo-test-10
  template:
    metadata:
      labels:
        app: jk-demo-test-10
        backstage.io/kubernetes-id: jk-demo-test-10
    spec:
      containers:
        - name: jk-demo-test-10
          image: jaykumark7/jk-demo-test-10:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


