apiVersion: v1
kind: Service
metadata:
  name: apr-27-demo-1
spec:
  selector:
    app: apr-27-demo-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: LoadBalancer

