apiVersion: apps/v1
kind: Deployment
metadata:
  name: april-13-test-1
  labels:
    app: april-13-test-1
    backstage.io/kubernetes-id: april-13-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: april-13-test-1
  template:
    metadata:
      labels:
        app: april-13-test-1
        backstage.io/kubernetes-id: april-13-test-1
    spec:
      containers:
        - name: april-13-test-1
          image: jaykumark7/april-13-test-1:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


