apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-feb-24-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-feb-24-1
  template:
    metadata:
      labels:
        app: demo-feb-24-1
        backstage.io/kubernetes-id: demo-feb-24-1
    spec:
      containers:
        - name: demo-feb-24-1
          image: jaykumark7/demo-feb-24-1:1.0.1
          imagePullPolicy: Always
          # ports:

          #   - containerPort: 3000
