apiVersion: apps/v1
kind: Deployment
metadata:
  name: mar-27-demo-4
  labels:
    app: mar-27-demo-4
    backstage.io/kubernetes-id: mar-27-demo-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mar-27-demo-4
  template:
    metadata:
      labels:
        app: mar-27-demo-4
        backstage.io/kubernetes-id: mar-27-demo-4
    spec:
      containers:
        - name: mar-27-demo-4
          image: jaykumark7/mar-27-demo-4:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


