apiVersion: v1
kind: Service
metadata:
  name: mar-27-demo-4
spec:
  selector:
    app: mar-27-demo-4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: LoadBalancer

