apiVersion: v1
kind: Service
metadata:
  name: jk-demo-test-2
spec:
  selector:
    app: jk-demo-test-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: LoadBalancer

