apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-test-2
  namespace: dev
  labels:
    app: springboot-test-2
    backstage.io/kubernetes-id: springboot-test-2
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-test-2
  template:
    metadata:
      labels:
        app: springboot-test-2
        backstage.io/kubernetes-id: springboot-test-2
        environment: dev
    spec:
      containers:
        - name: springboot-test-2
          image: jaykumark7/springboot-test-2:1.0.2
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "dev"
          resources:
            requests:
              memory: "384Mi"
              cpu: "250m"
            limits:
              memory: "1512Mi"
              cpu: "500m"
