# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: example-python-app-5
#   namespace: argocd
#   labels:
#     app.kubernetes.io/name: example-python-app-5
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/jk7testorg/k8s-manifest.git
#     targetRevision: main
#     path: apps/example-python-app-5
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-python-app-5-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jk7testorg/k8s-manifest.git
    targetRevision: main
    path: apps/example-python-app-5/qa
  destination:
    #server: https://kubernetes.default.svc
    server: https://34.61.160.224
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /metadata/annotations/argocd.argoproj.io~1tracking-id
    ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /metadata/annotations/argocd.argoproj.io~1tracking-id
