# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: example-repo
#   namespace: argocd
#   labels:
#     app.kubernetes.io/name: example-repo
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/jk7testorg/k8s-manifest.git
#     targetRevision: main
#     path: apps/example-repo
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-repo-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jk7testorg/k8s-manifest.git
    targetRevision: main
    path: apps/example-repo/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /metadata/annotations/argocd.argoproj.io~1tracking-id
    ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /metadata/annotations/argocd.argoproj.io~1tracking-id
