apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-python-test-15-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jk7testorg/k8s-manifest.git
    targetRevision: main
    path: apps/example-python-test-15/dev
  destination:
    server: https://8.34.212.149    
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true           
