apiVersion: v1
kind: Service
metadata:
  name: source-3-developer4
spec:
  selector:
    app: source-3-developer4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: LoadBalancer

