apiVersion: apps/v1
kind: Deployment
metadata:
  name: march-24-jenkins-test-2
  labels:
    app: march-24-jenkins-test-2
    backstage.io/kubernetes-id: march-24-jenkins-test-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: march-24-jenkins-test-2
  template:
    metadata:
      labels:
        app: march-24-jenkins-test-2
        backstage.io/kubernetes-id: march-24-jenkins-test-2
    spec:
      containers:
        - name: march-24-jenkins-test-2
          image: jaykumark7/march-24-jenkins-test-2:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


