apiVersion: v1
kind: Service
metadata:
  name: march-24-jenkins-test-2
spec:
  selector:
    app: march-24-jenkins-test-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: LoadBalancer

