apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldenimagetest3
  labels:
    app: goldenimagetest3
    backstage.io/kubernetes-id: goldenimagetest3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goldenimagetest3
  template:
    metadata:
      labels:
        app: goldenimagetest3
        backstage.io/kubernetes-id: goldenimagetest3
    spec:
      containers:
        - name: goldenimagetest3
          image: jaykumark7/goldenimagetest3:1.0.1
          imagePullPolicy: Always
          # ports:

          #   - containerPort: 3000

