apiVersion: v1
kind: Service
metadata:
  name: github-to-argo-playground
spec:
  selector:
    app: github-to-argo-playground
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: LoadBalancer

