apiVersion: apps/v1
kind: Deployment
metadata:
  name: jk7-mar-6
  labels:
    app: jk7-mar-6
    backstage.io/kubernetes-id: jk7-mar-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jk7-mar-6
  template:
    metadata:
      labels:
        app: jk7-mar-6
        backstage.io/kubernetes-id: jk7-mar-6
    spec:
      containers:
        - name: jk7-mar-6
          image: jaykumark7/jk7-mar-6:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


