apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-test-3
  namespace: dev
  labels:
    backstage.io/kubernetes-id: example-test-3
    environment: dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /example-test-3-dev(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: example-test-3
                port:
                  number: 80