apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-dns-test-4
  namespace: dev
  labels:
    app: no-dns-test-4
    backstage.io/kubernetes-id: no-dns-test-4
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: no-dns-test-4
  template:
    metadata:
      labels:
        app: no-dns-test-4
        backstage.io/kubernetes-id: no-dns-test-4
        environment: dev
    spec:
      containers:
        - name: no-dns-test-4
          image: jaykumark7/no-dns-test-4:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "dev"
          resources:
            requests:
              memory: "384Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
