apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-repo-new-1
  labels:
    app: example-repo-new-1
    backstage.io/kubernetes-id: example-repo-new-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-repo-new-1
  template:
    metadata:
      labels:
        app: example-repo-new-1
        backstage.io/kubernetes-id: example-repo-new-1
    spec:
      containers:
        - name: example-repo-new-1
          image: jaykumark7/example-repo-new-1:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


