apiVersion: v1
kind: Service
metadata:
  name: example-python-test-2
spec:
  selector:
    app: example-python-test-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: example-python-test-2-ingress
# spec:
#   ingressClassName: gce
#   rules:
#   - host: example-python-test-2.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: example-python-test-2
#             port:
#               number: 80
