apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-2-result-6
  labels:
    app: source-2-result-6
    backstage.io/kubernetes-id: source-2-result-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source-2-result-6
  template:
    metadata:
      labels:
        app: source-2-result-6
        backstage.io/kubernetes-id: source-2-result-6
    spec:
      containers:
        - name: source-2-result-6
          image: jaykumark7/source-2-result-6:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


