apiVersion: v1
kind: Service
metadata:
  name: java-ssp-13
  namespace: dev
  labels:
    backstage.io/kubernetes-id: java-ssp-13
spec:
  selector:
    app: java-ssp-13
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
