apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-repo-dev-12
  labels:
    app: example-repo-dev-12
    backstage.io/kubernetes-id: example-repo-dev-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-repo-dev-12
  template:
    metadata:
      labels:
        app: example-repo-dev-12
        backstage.io/kubernetes-id: example-repo-dev-12
    spec:
      containers:
        - name: example-repo-dev-12
          image: jaykumark7/example-repo-dev-12:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


