apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-ssp-4
  namespace: dev
  labels:
    app: java-ssp-4
    backstage.io/kubernetes-id: java-ssp-4
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-ssp-4
  template:
    metadata:
      labels:
        app: java-ssp-4
        backstage.io/kubernetes-id: java-ssp-4
        environment: dev
    spec:
      containers:
        - name: java-ssp-4
          image: jaykumark7/java-ssp-4:1.0.4
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "dev"
