apiVersion: v1
kind: Service
metadata:
  name: march-27-test-21
spec:
  selector:
    app: march-27-test-21
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: LoadBalancer

