apiVersion: v1
kind: Service
metadata:
  name: example-repo-new-6
spec:
  selector:
    app: example-repo-new-6
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: Loavtkghjmalancer

