apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-3-app-2-developer2
  labels:
    app: source-3-app-2-developer2
    backstage.io/kubernetes-id: source-3-app-2-developer2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source-3-app-2-developer2
  template:
    metadata:
      labels:
        app: source-3-app-2-developer2
        backstage.io/kubernetes-id: source-3-app-2-developer2
    spec:
      containers:
        - name: source-3-app-2-developer2
          image: jaykumark7/source-3-app-2-developer2:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


