apiVersion: v1
kind: Service
metadata:
  name: source-3-app-2-developer2
spec:
  selector:
    app: source-3-app-2-developer2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: LoadBalancer

