apiVersion: apps/v1
kind: Deployment
metadata:
  name: jk7-mar-8
  labels:
    app: jk7-mar-8
    backstage.io/kubernetes-id: jk7-mar-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jk7-mar-8
  template:
    metadata:
      labels:
        app: jk7-mar-8
        backstage.io/kubernetes-id: jk7-mar-8
    spec:
      containers:
        - name: jk7-mar-8
          image: jaykumark7/jk7-mar-8:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


