apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-feb-24-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-feb-24-2
  template:
    metadata:
      labels:
        app: demo-feb-24-2
        backstage.io/kubernetes-id: demo-feb-24-2
    spec:
      containers:
        - name: demo-feb-24-2
          image: jaykumark7/demo-feb-24-2:1.0.1
          imagePullPolicy: Always
          # ports:

          #   - containerPort: 3000
