apiVersion: v1
kind: Service
metadata:
  name: backstage-ssp-03
spec:
  selector:
    app: backstage-ssp-03
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: LoadBalancer

