apiVersion: v1
kind: Service
metadata:
  name: springboot-test-1
  namespace: dev
  labels:
    backstage.io/kubernetes-id: springboot-test-1
spec:
  selector:
    app: springboot-test-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
