apiVersion: v1
kind: Service
metadata:
  name: march-demo-1
spec:
  selector:
    app: march-demo-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

  type: LoadBalancer
