apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-dns-test-3
  namespace: dev
  labels:
    app: no-dns-test-3
    backstage.io/kubernetes-id: no-dns-test-3
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: no-dns-test-3
  template:
    metadata:
      labels:
        app: no-dns-test-3
        backstage.io/kubernetes-id: no-dns-test-3
        environment: dev
    spec:
      containers:
        - name: no-dns-test-3
          image: jaykumark7/no-dns-test-3:1.0.3
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "dev"
          resources:
            requests:
              memory: "384Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
